(cl:in-package schneider_104-srv)
(cl:export '(MEMOIRE-VAL
          MEMOIRE
          ST8-VAL
          ST8
          ST9-VAL
          ST9
          ST10-VAL
          ST10
          ST11-VAL
          ST11
          ST12-VAL
          ST12
          ST13-VAL
          ST13
          ST14-VAL
          ST14
          ST15-VAL
          ST15
          ST16-VAL
          ST16
          ST17-VAL
          ST17
          R5D-VAL
          R5D
          R6D-VAL
          R6D
          R7D-VAL
          R7D
          R8D-VAL
          R8D
          R5G-VAL
          R5G
          R6G-VAL
          R6G
          R7G-VAL
          R7G
          R8G-VAL
          R8G
          PI3-VAL
          PI3
          PI4-VAL
          PI4
          PI5-VAL
          PI5
          PI6-VAL
          PI6
          D5-VAL
          D5
          D6-VAL
          D6
          D7-VAL
          D7
          D8-VAL
          D8
          V5-VAL
          V5
          V6-VAL
          V6
          V7-VAL
          V7
          V8-VAL
          V8
          PS8-VAL
          PS8
          PS9-VAL
          PS9
          PS10-VAL
          PS10
          PS11-VAL
          PS11
          PS12-VAL
          PS12
          PS13-VAL
          PS13
          PS14-VAL
          PS14
          PS15-VAL
          PS15
          PS16-VAL
          PS16
          PS17-VAL
          PS17
          D5D-VAL
          D5D
          D6D-VAL
          D6D
          D7D-VAL
          D7D
          D8D-VAL
          D8D
          D5G-VAL
          D5G
          D6G-VAL
          D6G
          D7G-VAL
          D7G
          D8G-VAL
          D8G
          CPI3-VAL
          CPI3
          CPI4-VAL
          CPI4
          CPI5-VAL
          CPI5
          CPI6-VAL
          CPI6
          CP4-VAL
          CP4
          CP5-VAL
          CP5
          CP6-VAL
          CP6
          CP7-VAL
          CP7
))