// Generated by gencpp from file schneider/Retour_cellule.msg
// DO NOT EDIT!


#ifndef SCHNEIDER_MESSAGE_RETOUR_CELLULE_H
#define SCHNEIDER_MESSAGE_RETOUR_CELLULE_H

#include <ros/service_traits.h>


#include <schneider/Retour_celluleRequest.h>
#include <schneider/Retour_celluleResponse.h>


namespace schneider
{

struct Retour_cellule
{

typedef Retour_celluleRequest Request;
typedef Retour_celluleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Retour_cellule
} // namespace schneider


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::schneider::Retour_cellule > {
  static const char* value()
  {
    return "c63fcfc82e9baf3268db909f613de20c";
  }

  static const char* value(const ::schneider::Retour_cellule&) { return value(); }
};

template<>
struct DataType< ::schneider::Retour_cellule > {
  static const char* value()
  {
    return "schneider/Retour_cellule";
  }

  static const char* value(const ::schneider::Retour_cellule&) { return value(); }
};


// service_traits::MD5Sum< ::schneider::Retour_celluleRequest> should match
// service_traits::MD5Sum< ::schneider::Retour_cellule >
template<>
struct MD5Sum< ::schneider::Retour_celluleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::schneider::Retour_cellule >::value();
  }
  static const char* value(const ::schneider::Retour_celluleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::schneider::Retour_celluleRequest> should match
// service_traits::DataType< ::schneider::Retour_cellule >
template<>
struct DataType< ::schneider::Retour_celluleRequest>
{
  static const char* value()
  {
    return DataType< ::schneider::Retour_cellule >::value();
  }
  static const char* value(const ::schneider::Retour_celluleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::schneider::Retour_celluleResponse> should match
// service_traits::MD5Sum< ::schneider::Retour_cellule >
template<>
struct MD5Sum< ::schneider::Retour_celluleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::schneider::Retour_cellule >::value();
  }
  static const char* value(const ::schneider::Retour_celluleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::schneider::Retour_celluleResponse> should match
// service_traits::DataType< ::schneider::Retour_cellule >
template<>
struct DataType< ::schneider::Retour_celluleResponse>
{
  static const char* value()
  {
    return DataType< ::schneider::Retour_cellule >::value();
  }
  static const char* value(const ::schneider::Retour_celluleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHNEIDER_MESSAGE_RETOUR_CELLULE_H
