// Generated by gencpp from file schneider_103/Retour_cellule_103.msg
// DO NOT EDIT!


#ifndef SCHNEIDER_103_MESSAGE_RETOUR_CELLULE_103_H
#define SCHNEIDER_103_MESSAGE_RETOUR_CELLULE_103_H

#include <ros/service_traits.h>


#include <schneider_103/Retour_cellule_103Request.h>
#include <schneider_103/Retour_cellule_103Response.h>


namespace schneider_103
{

struct Retour_cellule_103
{

typedef Retour_cellule_103Request Request;
typedef Retour_cellule_103Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Retour_cellule_103
} // namespace schneider_103


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::schneider_103::Retour_cellule_103 > {
  static const char* value()
  {
    return "144215a6005e994c4be2aa0a861077f5";
  }

  static const char* value(const ::schneider_103::Retour_cellule_103&) { return value(); }
};

template<>
struct DataType< ::schneider_103::Retour_cellule_103 > {
  static const char* value()
  {
    return "schneider_103/Retour_cellule_103";
  }

  static const char* value(const ::schneider_103::Retour_cellule_103&) { return value(); }
};


// service_traits::MD5Sum< ::schneider_103::Retour_cellule_103Request> should match
// service_traits::MD5Sum< ::schneider_103::Retour_cellule_103 >
template<>
struct MD5Sum< ::schneider_103::Retour_cellule_103Request>
{
  static const char* value()
  {
    return MD5Sum< ::schneider_103::Retour_cellule_103 >::value();
  }
  static const char* value(const ::schneider_103::Retour_cellule_103Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::schneider_103::Retour_cellule_103Request> should match
// service_traits::DataType< ::schneider_103::Retour_cellule_103 >
template<>
struct DataType< ::schneider_103::Retour_cellule_103Request>
{
  static const char* value()
  {
    return DataType< ::schneider_103::Retour_cellule_103 >::value();
  }
  static const char* value(const ::schneider_103::Retour_cellule_103Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::schneider_103::Retour_cellule_103Response> should match
// service_traits::MD5Sum< ::schneider_103::Retour_cellule_103 >
template<>
struct MD5Sum< ::schneider_103::Retour_cellule_103Response>
{
  static const char* value()
  {
    return MD5Sum< ::schneider_103::Retour_cellule_103 >::value();
  }
  static const char* value(const ::schneider_103::Retour_cellule_103Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::schneider_103::Retour_cellule_103Response> should match
// service_traits::DataType< ::schneider_103::Retour_cellule_103 >
template<>
struct DataType< ::schneider_103::Retour_cellule_103Response>
{
  static const char* value()
  {
    return DataType< ::schneider_103::Retour_cellule_103 >::value();
  }
  static const char* value(const ::schneider_103::Retour_cellule_103Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHNEIDER_103_MESSAGE_RETOUR_CELLULE_103_H
