// Generated by gencpp from file schneider_104/Retour_cellule_104.msg
// DO NOT EDIT!


#ifndef SCHNEIDER_104_MESSAGE_RETOUR_CELLULE_104_H
#define SCHNEIDER_104_MESSAGE_RETOUR_CELLULE_104_H

#include <ros/service_traits.h>


#include <schneider_104/Retour_cellule_104Request.h>
#include <schneider_104/Retour_cellule_104Response.h>


namespace schneider_104
{

struct Retour_cellule_104
{

typedef Retour_cellule_104Request Request;
typedef Retour_cellule_104Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Retour_cellule_104
} // namespace schneider_104


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::schneider_104::Retour_cellule_104 > {
  static const char* value()
  {
    return "da2dff768924005c2c1434c86e6e1a14";
  }

  static const char* value(const ::schneider_104::Retour_cellule_104&) { return value(); }
};

template<>
struct DataType< ::schneider_104::Retour_cellule_104 > {
  static const char* value()
  {
    return "schneider_104/Retour_cellule_104";
  }

  static const char* value(const ::schneider_104::Retour_cellule_104&) { return value(); }
};


// service_traits::MD5Sum< ::schneider_104::Retour_cellule_104Request> should match
// service_traits::MD5Sum< ::schneider_104::Retour_cellule_104 >
template<>
struct MD5Sum< ::schneider_104::Retour_cellule_104Request>
{
  static const char* value()
  {
    return MD5Sum< ::schneider_104::Retour_cellule_104 >::value();
  }
  static const char* value(const ::schneider_104::Retour_cellule_104Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::schneider_104::Retour_cellule_104Request> should match
// service_traits::DataType< ::schneider_104::Retour_cellule_104 >
template<>
struct DataType< ::schneider_104::Retour_cellule_104Request>
{
  static const char* value()
  {
    return DataType< ::schneider_104::Retour_cellule_104 >::value();
  }
  static const char* value(const ::schneider_104::Retour_cellule_104Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::schneider_104::Retour_cellule_104Response> should match
// service_traits::MD5Sum< ::schneider_104::Retour_cellule_104 >
template<>
struct MD5Sum< ::schneider_104::Retour_cellule_104Response>
{
  static const char* value()
  {
    return MD5Sum< ::schneider_104::Retour_cellule_104 >::value();
  }
  static const char* value(const ::schneider_104::Retour_cellule_104Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::schneider_104::Retour_cellule_104Response> should match
// service_traits::DataType< ::schneider_104::Retour_cellule_104 >
template<>
struct DataType< ::schneider_104::Retour_cellule_104Response>
{
  static const char* value()
  {
    return DataType< ::schneider_104::Retour_cellule_104 >::value();
  }
  static const char* value(const ::schneider_104::Retour_cellule_104Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHNEIDER_104_MESSAGE_RETOUR_CELLULE_104_H
